<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<UseWPF>true</UseWPF>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>

		<TargetFramework Label="Visual Studio 2022 Target" Condition="'$(VisualStudioVersion)' == '17.0'">net8.0-windows</TargetFramework>
		<TargetFramework Label="Default Target" Condition="'$(TargetFramework)' == ''">net10.0-windows</TargetFramework>

		<Version>26.1.0$(PreReleaseTagWithDash)</Version>

		<DefineConstants>CODE_ANALYSIS;WPF;DESKTOP</DefineConstants>

		<AssemblyName>SampleBrowser</AssemblyName>
		<Product>WPF Controls Sample Browser</Product>
		<Title>WPF Controls Sample Browser</Title>
		<Description>Sample application to demo features of the Actipro WPF controls.</Description>

		<AssemblyTitle>$(Title)</AssemblyTitle>

		<Company>Actipro Software LLC</Company>
		<Authors>Actipro Software LLC</Authors>
		<Copyright>Copyright (c) 2007-2026 Actipro Software LLC</Copyright>

		<ApplicationIcon>Images\Icons\Actipro.ico</ApplicationIcon>
		<ApplicationManifest>Properties\app.manifest</ApplicationManifest>

		<RootNamespace>ActiproSoftware</RootNamespace>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<ApplicationDefinition Include="SampleBrowser\App.xaml" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Images\**\*.*" />
		<Resource Include="ProductSamples\**\*.xml" />
		<Resource Include="ProductSamples\**\Images\*.*" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\Definitions\**\*.langdef" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\Snippets\**\*.snippet*" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\Themes\**\*.vssettings" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\XmlSchemas\**\*.html" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\XmlSchemas\**\*.xml" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\XmlSchemas\**\*.xsd" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\XmlSchemas\**\*.xslt" />
	</ItemGroup>

	<ItemGroup>
		<None Include="ProductSamples\SyntaxEditorSamples\**\*.langproj" />
	</ItemGroup>

	<ItemGroup Label="External Assembly References">
		<Reference Include="TransitionEffects">
			<HintPath>ReferencedAssemblies\TransitionEffects-2.0\TransitionEffects.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup Label=".NET Framework References" Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
		<Reference Include="ReachFramework" />
		<Reference Include="System.ComponentModel.DataAnnotations" />
		<Reference Include="System.Printing" />
	</ItemGroup>

	<ItemGroup Label=".NET References" Condition="'$(TargetFramework)' == 'net8.0-windows' or '$(TargetFramework)' == 'net9.0-windows'">
		<PackageReference Include="System.Drawing.Common" Version="4.7.2" />
	</ItemGroup>

	<!-- Define Actipro assembly references -->
	<Import Project="ActiproSoftware.References.props" />

</Project>