namespace ActiproSoftware.ProductSamples.SyntaxEditorSamples.QuickStart.DotNetAddOnServerTags {
    using ActiproSoftware.Text;
    
    
    /// <summary>
    /// Provides the base requirements of an object that provides <see cref="IClassificationType"/> objects for the <c>Parent to C# example</c> language.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v14.2.610.0 (http://www.actiprosoftware.com).
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LanguageDesigner", "14.2.610.0")]
    public interface IParentClassificationTypeProvider {
        
        /// <summary>
        /// Gets the <c>Keyword</c> classification type.
        /// </summary>
        /// <value>The <c>Keyword</c> classification type.</value>
        IClassificationType Keyword {
            get;
        }
        
        /// <summary>
        /// Gets the <c>TransitionDelimiter</c> classification type.
        /// </summary>
        /// <value>The <c>TransitionDelimiter</c> classification type.</value>
        IClassificationType TransitionDelimiter {
            get;
        }
    }
}
