<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>

		<AssemblyName>ActiproSoftware.Editors.Interop.DataGrid.Wpf</AssemblyName>
		<Product>Editors.Interop.DataGrid</Product>
		<Title>Actipro Editors/DataGrid Interop (for WPF)</Title>
		<Description>Provides interoperability between Actipro's WPF Editors product and the WPF DataGrid.</Description>
		<PackageTags>Actipro UI Controls WPF XAML Editors DataGrid</PackageTags>

		<AssemblyTitle>$(Title)</AssemblyTitle>

		<RootNamespace>ActiproSoftware</RootNamespace>

		<DefineConstants>CODE_ANALYSIS;WPF;DESKTOP</DefineConstants>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageProjectUrl>https://www.actiprosoftware.com/products/controls/wpf</PackageProjectUrl>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>..\bin\Debug</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>..\bin\Release</OutputPath>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="ActiproSoftware.Controls.WPF.Editors" Version="26.1.0-rc.5" />
	</ItemGroup>

</Project>
