<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>

		<AssemblyName>ActiproSoftware.Bars.Mvvm.Wpf</AssemblyName>
		<Product>Bars.Mvvm</Product>
		<Title>Actipro Bars MVVM (for WPF)</Title>
		<Description>Common view models, templates, and other types used when implementing Bars controls with MVVM (Model-View-ViewModel) patterns.</Description>
		<PackageTags>Actipro UI Controls WPF XAML MVVM Model View ViewModel Bars</PackageTags>

		<AssemblyTitle>$(Title)</AssemblyTitle>

		<RootNamespace>ActiproSoftware</RootNamespace>

		<DefineConstants>CODE_ANALYSIS;WPF;DESKTOP</DefineConstants>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageProjectUrl>https://www.actiprosoftware.com/products/controls/wpf</PackageProjectUrl>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>..\bin\Debug</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>..\bin\Release</OutputPath>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ActiproSoftware.Controls.WPF.Bars" Version="26.1.0-rc.5" />
	</ItemGroup>

	<ItemGroup Label=".NET Framework" Condition="'$(TargetFramework)' == 'net462'">
		<Reference Include="System.ComponentModel.DataAnnotations" />
	</ItemGroup>
	
</Project>
