namespace ActiproSoftware.ProductSamples.SyntaxEditorSamples.QuickStart.GettingStarted04d {
    using ActiproSoftware.Text.Parsing;
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// Represents a block statement.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v11.1.544.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Actipro Software LLC.
    /// Copyright (c) 2001-2023 Actipro Software LLC.  All rights reserved.
    /// </remarks>
    public partial class BlockStatement : Statement {
        
        /// <summary>
        /// Gets the child statements.
        /// </summary>
        private IList<Statement> childStatementsValue;
        
        /// <summary>
        /// Gets the An integer value that identifies the type of AST node.
        /// </summary>
        /// <value>The An integer value that identifies the type of AST node.</value>
        public override Int32 Id {
            get {
                return SimpleAstNodeId.BlockStatement;
            }
        }
        
        /// <summary>
        /// Gets the child statements.
        /// </summary>
        /// <value>The child statements.</value>
        public IList<Statement> ChildStatements {
            get {
                if ((this.childStatementsValue == null)) {
                    this.childStatementsValue = new List<Statement>();
                }
                return this.childStatementsValue;
            }
        }
        
        /// <summary>
        /// Returns whether the <see cref="ChildStatements"/> collection property contains at least one item.
        /// </summary>
        /// <value><c>true</c> if there is at least one item in the collection; otherwise, <c>false</c>.</value>
        public Boolean HasChildStatements {
            get {
                if (((this.childStatementsValue != null) 
                            && (this.childStatementsValue.Count > 0))) {
                    return true;
                }
                else {
                    return false;
                }
            }
        }
        
        /// <summary>
        /// Retrieves an <c>IEnumerator</c> object that can iterate the child <see cref="IAstNode"/> objects in this node.
        /// </summary>
        /// <returns>An <c>IEnumerator</c> object that can iterate the child <see cref="IAstNode"/> objects in this node.</returns>
        protected override IEnumerator<IAstNode> GetChildrenEnumerator() {
            IEnumerator<IAstNode> baseEnumerator = base.GetChildrenEnumerator();
            if ((baseEnumerator != null)) {
				while (baseEnumerator.MoveNext())
					yield return baseEnumerator.Current;
            }
            if ((this.childStatementsValue != null)) {
				foreach (IAstNode childStatementsValueItem in this.childStatementsValue)
					if (childStatementsValueItem != null) yield return childStatementsValueItem;
            }
        }
    }
}
