namespace ActiproSoftware.ProductSamples.SyntaxEditorSamples.QuickStart.GettingStarted04d {
    using ActiproSoftware.Text.Parsing;
    using System;
    
    
    /// <summary>
    /// Represents a literal expression.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v11.1.544.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Actipro Software LLC.
    /// Copyright (c) 2001-2021 Actipro Software LLC.  All rights reserved.
    /// </remarks>
    public partial class LiteralExpression : Expression {
        
        /// <summary>
        /// Gets the kind.
        /// </summary>
        private LiteralExpressionKind kindValue;
        
        /// <summary>
        /// Gets the string value.
        /// </summary>
        private String stringValueValue;
        
        /// <summary>
        /// Gets the An integer value that identifies the type of AST node.
        /// </summary>
        /// <value>The An integer value that identifies the type of AST node.</value>
        public override Int32 Id {
            get {
                return SimpleAstNodeId.LiteralExpression;
            }
        }
        
        /// <summary>
        /// Gets or sets the kind.
        /// </summary>
        /// <value>The kind.</value>
        public LiteralExpressionKind Kind {
            get {
                return this.kindValue;
            }
            set {
                this.kindValue = value;
            }
        }
        
        /// <summary>
        /// Gets or sets the string value.
        /// </summary>
        /// <value>The string value.</value>
        public String StringValue {
            get {
                return this.stringValueValue;
            }
            set {
                this.stringValueValue = value;
            }
        }
    }
}
