namespace ActiproSoftware.ProductSamples.SyntaxEditorSamples.QuickStart.GettingStarted04d {
    using ActiproSoftware.Text.Parsing;
    using System;
    
    
    /// <summary>
    /// Represents a simple name.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v11.1.544.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Actipro Software LLC.
    /// Copyright (c) 2001-2022 Actipro Software LLC.  All rights reserved.
    /// </remarks>
    public partial class SimpleName : Expression {
        
        /// <summary>
        /// Gets the text value of the identifier.
        /// </summary>
        private String textValue;
        
        /// <summary>
        /// Gets the An integer value that identifies the type of AST node.
        /// </summary>
        /// <value>The An integer value that identifies the type of AST node.</value>
        public override Int32 Id {
            get {
                return SimpleAstNodeId.SimpleName;
            }
        }
        
        /// <summary>
        /// Gets or sets the text value of the identifier.
        /// </summary>
        /// <value>The text value of the identifier.</value>
        public String Text {
            get {
                return this.textValue;
            }
            set {
                this.textValue = value;
            }
        }
    }
}
