<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<UseWPF>true</UseWPF>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>

		<TargetFramework>net472</TargetFramework>

		<Version>26.1.0$(PreReleaseTagWithDash)</Version>

		<Company>Actipro Software LLC</Company>
		<Authors>Actipro Software LLC</Authors>
		<Copyright>Copyright (c) 2007-2026 Actipro Software LLC</Copyright>

		<ApplicationIcon>Actipro.ico</ApplicationIcon>

		<RootNamespace>ActiproSoftware.Windows.WindowsWorkflowIntegration</RootNamespace>
		<Title>Windows Workflow Integration Sample</Title>
		<Product>$(Title)</Product>
		<Description>Sample application to demonstrate integrating into a Windows Workflow application.</Description>

	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Actipro.ico" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Readme.txt" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="System.Activities" />
		<Reference Include="System.Activities.Core.Presentation" />
		<Reference Include="System.Activities.Presentation" />
	</ItemGroup>

	<!-- Define Actipro assembly references -->
	<Import Project="ActiproSoftware.References.props" />

</Project>