<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>

		<AssemblyName>ActiproSoftware.DataGrid.Contrib.Wpf</AssemblyName>
		<Product>DataGrid.Contrib</Product>
		<Title>Actipro DataGrid Contrib (for WPF)</Title>
		<Description>Common extensions, behaviors, and themes for the WPF DataGrid control.</Description>
		<PackageTags>Actipro UI Controls WPF XAML DataGrid</PackageTags>

		<AssemblyTitle>$(Title)</AssemblyTitle>

		<RootNamespace>ActiproSoftware</RootNamespace>

		<DefineConstants>CODE_ANALYSIS;WPF;DESKTOP</DefineConstants>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageProjectUrl>https://www.actiprosoftware.com/products/controls/wpf</PackageProjectUrl>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>..\bin\Debug</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>..\bin\Release</OutputPath>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ActiproSoftware.Controls.WPF.Shared" Version="26.1.0-rc.9" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Cursors\*.cur" />
		<Resource Include="Images\*.xaml">
		  <SubType>Designer</SubType>
		  <Generator>MSBuild:Compile</Generator>
		</Resource>
		<EmbeddedResource Include="Toolbox\*.png" />
	</ItemGroup>

</Project>
